### ISSUE TITLE
Enabling UART/RS232

### ISSUE THREAD

**Issue by gazzer82** [nerves-project/nerves_system_grisp2#52]
### Environment

* Elixir version (`elixir -v`): Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
* Nerves environment: (`mix nerves.env --info`)
```
A new version of Nerves bootstrap is available(1.11.4 < 1.11.5), You can update by running

  mix local.nerves

|nerves_bootstrap| Environment Package List

  No packages found
|nerves_bootstrap| Loadpaths Start

|nerves_bootstrap| Precompile Start

|nerves_bootstrap| Precompile End


Nerves environment
  MIX_TARGET:   host
  MIX_ENV:      dev

NERVES_SYSTEM is unset
NERVES_TOOLCHAIN is unset
|nerves_bootstrap| Environment Variable List
  target:     host
  toolchain:  unset
  system:     unset
  app:        .

|nerves_bootstrap| Loadpaths End
```
* Additional information about your host, target hardware or environment that
  may help

Actually testing this currently using the latest Nerves Livebook firmware, v0.10.0

### Current behavior

I am attempting to use the UART port on the Grisp2 board as a RS232 port for connecting to an external network switch. I have connected the PmodRS232 to, Pmod board facing upwards, and connected to the bottom row of the Pmod connector (which I THINK is the correct pinout). I have the JP1 on the board removed to disable flow control e.t.c

However when using circuits.UART I am unable to read anything from the port, which I believe should be "ttymxc3", I have even just looped the TX back into the RX on the RS232 connector and still have nothing coming back on the port.

There's a very strong possibility that I've misunderstood the port mapping on this though, and I can see a reference to /dev/ttyS3 in the [linux/imx6ul-grisp2.dts‎](https://github.com/nerves-project/nerves_system_grisp2/blob/17a2c6d06961544737919e4d4fdc07165a126be2/linux/imx6ul-grisp2.dts#L131) file, that might imply that I need to configure that port to be UART rather than GPIO, but I'm not really sure how to go about that?

### Expected behavior
To be able to open the Pmod UART port and communicate with another device over RS223, using the PmodRS232 module.

Thanks

**Comment by fhunleth** [comment]
Hi @gazzer82,

I never ported the device tree for the UART port so that it would work with Linux (and Nerves). Just on inspection, the `grisp,uartdev` won't do anything on Linux. I'd have to look harder at it, but trying other `ttymxc` devices might be worth it to see if you can get lucky. 

I might have some time next week to look at it. If you or anyone else figures out the problem, though, please let me know and I'll make a `nerves_system_grisp2` release with the fix.

**Comment by gazzer82** [comment]
Hi @fhunleth thanks for the reply.

I have tried the two available ports, ttymxc0, and ttymxc7.

On ttymxc0 I seem to get a constant stream of the following:

```
{:circuits_uart, "ttymxc0", <<255, 255, 255, 255, 255, 255, 255, 255, 255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<223>>}
{:circuits_uart, "ttymxc0", <<255, 255, 251>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
{:circuits_uart, "ttymxc0", <<255>>}
```

Despite there being nothing connected to the UART port, so I'm guessing this is being logged to by Nerves or something similar.

On ttymxc7 I never get anything back, even if I physically loop the tx/rx ports back around on each other, either on the UART or RS232 header. So assuming that's not going anywhere.

I'm not sure I even know where to start with a device tree for Nerves, but seems as good a time to try and learn as ever, so I'll see what I can work out!

Cheers

Gareth

**Comment by fhunleth** [comment]
I saw your Elixir forum post and shared it on the GRiSP channel on the Erlang slack. I figured that it was worth a try since that's where the majority of GRiSP users hang out.

**Comment by gazzer82** [comment]
Ah thanks! I did try to signup for the Erlang slack, but the invite never came through.

**Comment by fhunleth** [comment]
No worries. If anyone says anything, I'll repost. If it's actionable, I'll make a PR since it will probably be a one or two line change in the end.

**Comment by gazzer82** [comment]
Great, would be good to see what the changes are, if any, so I can improve my understanding of how the hardware side of things works with Nerves. It's not a strong point of mine.

Not sure if it's worth mentioning on the Slack, but it does seem the "Request an Invite" link to join the Erlang slack is Broken. I just get a `An unknown error occurred while processing your request. Please try again` message whenever I tr to submit it.

**Comment by peerst** [comment]
Regarding the pin out I answered in Elixir Forum.

Regarding Slack signup: I’d like go know more.  Which link did you use?  The one on Erlang.org?

**Comment by gazzer82** [comment]
Yes just saw that, can't believe I didn't see that 1 on the board . . . . will try looping the UART/RS232 port on pins 2/3 and see if I get any further forward, will report back on the forum.

Yes the Slack link was via the Erlang.org page

<img width="1246" alt="Screenshot 2023-07-19 at 16 25 02" src="https://github.com/nerves-project/nerves_system_grisp2/assets/1923535/40e3340d-9f29-4e07-927a-1ff6871a4728">

**Comment by starbelly** [comment]
hey @gazzer82 . We should provide a more useful error message here, but I'd bet if you check your email you might have gotten one from slack stating you already have a login for said email address.

**Comment by gazzer82** [comment]
Would you prefer me to be continue the thread on this here, or on the Elixir forum?

**Comment by fhunleth** [comment]
@gazzer82 I tried it out and saw that Linux set up UART4, but didn't configure pinmux to route UART4 to the UART PMOD pins. I fixed that in the Nerves section at the end of the device tree file. 

Are you comfortable with Nerves to try this out? If not and you can wait a day or two more, I'm going to try out a couple other things with the GRiSP2 while it's convenient for me and push a new release out.

**Comment by fhunleth** [comment]
@gazzer82 I released [nerves_system_grisp2 v0.7.1](https://github.com/nerves-project/nerves_system_grisp2/releases/tag/v0.7.1) with the UART device tree update. I think that it should work for you now.

**Comment by gazzer82** [comment]
@fhunleth just updated to the last build and that's fixed, many thanks. If you have 2 minutes, could you explain what you did to check what Linux was doing with the UART ports, and what section you've added at end of the device tree actually does. It's something I've looked at, but the syntax is a little alien to me. That or any resources you would recommend to get a better understanding of how the hardware mapping side of things works?

**Comment by fhunleth** [comment]
@gazzer82 My first step was to double check the device tree and the schematic to see that `ttymxc3` was the right UART. For reasons, it is very frequent that UART1 on the schematic is labelled as `0` in Linux, etc., and I wanted to double check that I wasn't doing something silly. The second step was to check the pinmux settings. This is more of an experience thing since if UARTs don't work and there's not an error in the dmesg, it's almost always a misconfigured pinmux setting. 

Here's the change annotated:

```
&uart4 {
	pinctrl-names = "default";
	pinctrl-0 = <&pinctrl_uart4>;
	status = "okay";
};
```

The `&uart4` means to modify the `uart4` definition at https://git.phytec.de/linux-mainline/tree/arch/arm/boot/dts/imx6ul.dtsi?h=v5.15.102-phy#n1072 (that file is included if you follow the includes at the top). The `status = "okay";` part tells Linux to enable UART4. This part wasn't necessary, but I like it since when I maintain device trees, seeing that the UART is enabled saves me a search. When Linux sees `pinctrl-*` definitions in a device that loads a driver, it calls the pinmux driver to set the configuration. That was the key. Linux ignores the `pmod-uart` code at https://github.com/nerves-project/nerves_system_grisp2/blob/main/linux/imx6ul-grisp2.dts#L124C2-L143, since no device driver is associated with it. 

The key to understanding device trees is just to view them as dumping grounds for whatever you want. When the Linux kernel sees something it knows about, it will do something. 

To figure out where the docs are, look for the `compatible=` field and then look in Linux's Documentation/devicetree directory for something that matches. For example, https://git.phytec.de/linux-mainline/tree/Documentation/devicetree/bindings/serial/fsl-imx-uart.yaml?h=v5.15.102-phy. Copy/pasting other people's device tree code works sometimes, but other times you just start putting in tons of unused lines that Linux ignores.
